### ISSUE TITLE
Support signal syscalls

### ISSUE THREAD

**Issue by Yourens** [occlum/libos#24]
To support Bash, here are some signal syscall we need.

syscall | description 
------- | --------------------------
rt_sigprocmask | With arguments SIG_SETMASK/SIG_BLOCK/SIG_UNBLOCK
rt_sigaction | With arguments SIGCHLD/SIGINT/SIGQUIT/SIGTSTP/SIGTTIN/SIGTTOU

**Comment by tatetian** [comment]
Signal is not a must for our purpose of running benchmarks. So this is not a priority.
